# Generated by Django 3.2.3 on 2021-05-22 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True)),
                ('set_pro_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('pro_pic', models.CharField(max_length=400)),
                ('country', models.TextField(blank=True, choices=[('Afghanistan', 'Afghanistan'), ('Bangladesh', 'Bangladesh'), ('Egypt', 'Egypt'), ('Pakistan', 'Pakistan'), ('Turkey', 'Turkey'), ('UAE', 'UAE'), ('UK', 'UK'), ('USA', 'USA'), ('Zimbabwe', 'Zimbabwe')], default='')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('facebook_profile', models.URLField(blank=True, verbose_name='Your Facebook Profile Link')),
                ('insta_profile', models.URLField(blank=True, verbose_name='Your Instagram Profile Link')),
                ('bio', models.TextField(blank=True, max_length=400, verbose_name='Write a short bio..')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
