# Generated by Django 3.2.3 on 2021-05-22 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_alter_userprofile_set_pro_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='set_pro_pic',
            field=models.ImageField(blank=True, default='', upload_to='profile_pics'),
        ),
    ]
