# Generated by Django 3.2.3 on 2021-05-15 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='comment_like',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='follow',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='post_like',
        ),
    ]
