# Generated by Django 3.2.3 on 2021-05-15 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20210516_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='comment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='comment_like',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='follow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='post_like',
            field=models.BooleanField(default=False),
        ),
    ]
