# Generated by Django 3.2.3 on 2021-05-22 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('Profile', '0004_auto_20210516_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
