# Generated by Django 3.2.3 on 2021-06-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('date',)},
        ),
        migrations.AddField(
            model_name='message',
            name='alert',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=2000, verbose_name='Type your message..'),
        ),
    ]
