# Generated by Django 3.2.3 on 2021-06-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0004_inboxalert_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='preview',
            field=models.CharField(default='', max_length=100),
        ),
    ]
