# Generated by Django 3.2.3 on 2021-06-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0005_message_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Type your message..'),
        ),
    ]
